name: flutter_client_php_backend
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.3.3
  cupertino_icons: ^0.1.2

flutter_icons:
  image_path: "assets/images/ic_launcher.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/ic_launcher.png
