name: flutter_client_php_backend
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.3.3
  shared_preferences: ^0.4.2
  json_annotation: ^0.2.4
  cupertino_icons: ^0.1.2
  http: ^0.11.3+16

flutter_icons:
  image_path: "assets/images/ic_launcher.png"
  android: true
  ios: true

dev_dependencies:
  build_runner: ^0.8.0
  json_serializable: ^0.5.2

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/ic_launcher.png
